module Constants
  APP_NAME = 'PomoColo'
  MAILER_SENDER_DISPLAY_NAME = 'PomoColo 事務局'
  PRODUCTION_HOST = 'pomocolo.herokuapp.com'
  FEED_NUM = 20
  COMMENT_NUM = 20
  SEARCH_USER_NUM = 20
  SEARCH_MICROPOST_NUM = 20
  SHOW_MICROPOST_NUM = 20
  SHOW_FOLLOW_NUM = 20
  NOTIFICATION_NUM = 30
  DEFAULT_TASK_TIME = 25
  DEFAULT_BREAK_TIME = 5
end
