module Constants
  APP_NAME = 'Pomodoro（仮）'
  MAILER_SENDER_DISPLAY_NAME = 'pomodoro3 事務局'
  PRODUCTION_HOST = 'pomodoro3new.herokuapp.com'
  FEED_NUM = 20
  COMMENT_NUM = 20
  SEARCH_USER_NUM = 20
  SEARCH_MICROPOST_NUM = 20
  SHOW_MICROPOST_NUM = 20
  SHOW_FOLLOW_NUM = 20
  NOTIFICATION_NUM = 30
  DEFAULT_TASK_TIME = 25
end
